---
# This playbook runs a basic DF command.

- name: ciao
  hosts: all
  #remote_user: root
  become: false
  gather _facts: false
  tasks:
    - name: find disk space available.
      ansible.windows.win_ping:
